citatelnost-algoritmu
Institut-zdravotnych-analyz/OSN-Algoritmus-MS-2024 pull request #8
Opened 2024-02-28 08:46 UTC by peterhutka

2024-02-28 12:09 UTC, matejmisik commented
Ahoj Peto, mergol som tam teraz jednu verziu a nastal tam conflict, pozrel by si pls na to?

2024-03-06 10:43 UTC, bielovico requested changes
Mam tam este nejaky komentar k tomu, ze v datach mame zoznamy diagnoz a vykonov, tak to by som este premenoval ale inak je to v tomto stave urcite good enough a sustredil sa na to zjednotenie algoritmov, pretoze inak to bude hrozny pain robit vzdy vsetky zmeny pre dva algoritmy

2024-03-06 10:43 UTC, bielovico commented on DRG-akykolvek-vykon/Algoritmus_v2.py
> +                diagnoza = data[5]
Premenoval by som diagnoza a vykon na `diagnozy` a `vykony` alebo `zoznam_diagnoz` a `zoznam_vykonov`

2024-03-20 11:10 UTC, bielovico commented
Navrhujem toto uzavrieť, chceme sa už venovať hlavne zjednotenému algoritmu a tieto pôvodné verzie časom zahodiť.

2024-06-07 11:36 UTC, closed without merging